@echo off
color A
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
echo %random% %random% %random% %random% %random% %random%
exit